// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceWar.Data;

#nullable disable

namespace SpaceWar.Data.Migrations
{
    [DbContext(typeof(SpaceWarContext))]
    [Migration("20241021100810_ship")]
    partial class ship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpaceWar.Core.Domain.Ship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BuiltAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DestroyedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrimaryAttack")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryAttack")
                        .HasColumnType("int");

                    b.Property<int>("ShipClass")
                        .HasColumnType("int");

                    b.Property<int>("ShipLevel")
                        .HasColumnType("int");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShipStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShipWasBuilt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ShipWasDestroyed")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShipXP")
                        .HasColumnType("int");

                    b.Property<int>("ShipXPNextLevel")
                        .HasColumnType("int");

                    b.Property<int>("UltimateAttack")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ships");
                });
#pragma warning restore 612, 618
        }
    }
}
